name: My First Workflow

on:
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: list and read file
        run: |
          echo "My First GitHub Action Job"
          ls -ltra
          cat README.md

      - name: Generate ASCII Artworks
        run: cowsay -f drgon "Run for cover, I am a DRAFON..RAWR" >> dragon.txt

        