name: My First Workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
i
      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAFON..RAWR" >> dragon.txt

      - name: Sleep for 30 seconds 
        run: sleep 30

  test_job:
     runs-on: ubuntu-latest
     steps:
      - name: Test file exists
        run: grep -i "dragon" dragon.txt
  deploy_job:
     runs_on: ubuntu-latest
    steps:
      - name: Read File
        run: cat dragon.txt
        
      - name: Deploy
        run: echo  Deploying... .. .      
