name: My ascii art work flow
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout the repository
            uses: actions/checkout@v7
        
          - name: Install cowsay Program
            run: sudo apt-get install cowsay -y

          - name: Execute cowsay CMD
            run: cowsay -f cat "Run for cover, I am a CAT...MEOWW" >> cat.txt
            
          - name: Test file Exists
            run: grep -i "cat" cat.txt
          
          - name: Read file
            run: cat cat.txt

          - name: List Repo files
            run: ls -ltra

        