name: variable secretes job level workflow
on: push

jobs:
############## enviroment variables at JOB level ################

    docker:
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: siddharth1
          IMAGE_NAME: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            # run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            
            - name: Docker Login
              env:
                DOCKER_PASSWORD: s3cUrePaSsw0rd
              run: docker login --username=$DOCKER_USERNAME --password=${{ env.DOCKER_PASSWORD }}
            
            - name: Docker Publish
              run: docker push docker.io/$DOCKER_USERNAME/$IMAGE_NAME:latest
    deploy:
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: siddharth1
          IMAGE_NAME: github-actions-nginx
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest